
---
# This role is intended to be used by *humans*, and is aggregated to the
# builtin 'admin' ClusterRole. By default, 'admin' doesn't get permissions
# to custom resources (see issue #1341).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - hnc.x-k8s.io
  resources:
  - '*'
  verbs:
  - '*'
